# Generated by Django 5.2.7 on 2025-12-03 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environment_conditions', models.CharField(choices=[('AC', 'Air-conditioned (Indoor)'), ('INDOOR', 'Indoor (Non Air-conditioned)'), ('OUTDOOR', 'Outdoor (Sheltered)')], max_length=8)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed')], default='PENDING', max_length=10)),
                ('price_per_day', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
                ('description', models.TextField()),
                ('num_rack', models.IntegerField(default=0)),
                ('num_shelves_per_rack', models.IntegerField(default=0)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.location')),
            ],
        ),
    ]
