# Generated by Django 5.2.7 on 2025-12-03 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(choices=[('AMK', 'Ang Mo Kio'), ('BDK', 'Bedok'), ('BSH', 'Bishan'), ('BLY', 'Boon Lay'), ('BBK', 'Bukit Batok'), ('BMR', 'Bukit Merah'), ('BPN', 'Bukit Panjang'), ('BTM', 'Bukit Timah'), ('CWC', 'Central Water Catchment'), ('CGI', 'Changi'), ('CGB', 'Changi Bay'), ('CLE', 'Clementi'), ('DTC', 'Downtown Core'), ('GEY', 'Geylang'), ('HOU', 'Hougang'), ('JES', 'Jurong East'), ('JWS', 'Jurong West'), ('KLL', 'Kallang'), ('LCK', 'Lim Chu Kang'), ('MAN', 'Mandai'), ('MAE', 'Marina East'), ('MAS', 'Marina South'), ('MPA', 'Marine Parade'), ('MUS', 'Museum'), ('NEW', 'Newton'), ('NEI', 'North-Eastern Islands'), ('NOV', 'Novena'), ('ORC', 'Orchard'), ('OUT', 'Outram'), ('PBL', 'Paya Lebar'), ('PIO', 'Pioneer'), ('PGL', 'Punggol'), ('PRS', 'Pasir Ris'), ('QTN', 'Queenstown'), ('RVL', 'River Valley'), ('RCH', 'Rochor'), ('SEL', 'Seletar'), ('SBW', 'Sembawang'), ('SKG', 'Sengkang'), ('SRG', 'Serangoon'), ('SMP', 'Simpang'), ('SGR', 'Singapore River'), ('SIS', 'Southern Islands'), ('SKT', 'Sungei Kadut'), ('STV', 'Straits View'), ('TMP', 'Tampines'), ('TGL', 'Tanglin'), ('TGH', 'Tengah'), ('TPY', 'Toa Payoh'), ('TUA', 'Tuas'), ('WIS', 'Western Islands'), ('WWC', 'Western Water Catchment'), ('WDL', 'Woodlands'), ('YSH', 'Yishun')], max_length=3)),
                ('address', models.CharField(max_length=200)),
                ('price_per_day', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.IntegerField(default=50)),
            ],
        ),
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shelf_label', models.CharField(max_length=3)),
                ('is_available', models.BooleanField(default=True)),
                ('rack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.rack')),
            ],
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environment_conditions', models.CharField(choices=[('AC', 'Air-conditioned (Indoor)'), ('INDOOR', 'Indoor (Non Air-conditioned)'), ('OUTDOOR', 'Outdoor (Sheltered)')], max_length=8)),
                ('height', models.IntegerField(default=42)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ON_HOLD', 'On Hold')], default='PENDING', max_length=8)),
                ('price_per_day', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
                ('description', models.TextField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.location')),
            ],
        ),
    ]
