# Generated by Django 5.2.7 on 2025-12-03 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_shelves_occupied', models.IntegerField(default=1)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('status', models.CharField(choices=[('BOOKED', 'Booked'), ('ACTIVE', 'Active'), ('PAST', 'Past'), ('CANCELLED', 'Cancelled')], default='BOOKED', max_length=10)),
                ('occupying_space', models.BooleanField(default=False)),
            ],
        ),
    ]
