# Generated by Django 5.2.7 on 2025-12-03 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('listings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='lessee',
            field=models.ForeignKey(limit_choices_to={'role': 'LESSEE'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='rack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.rack'),
        ),
    ]
